In [1]:
import numpy as np
import time
import random
import matplotlib.pyplot as plt
from IPython.display import Markdown, display
from IPython.display import clear_output

In [2]:
class FrozenLake(object):
    
    def __init__(self):
        self.location=[0,0]
        print("Welcome to Frozen Lake!! We are a Visual Guide to Help Understand You Q Learning")
        print("Please Enter Your Lake Dimensions:")
        print("")
        self.row=int(input("Row: "))
        self.col=int(input("Column: "))
        row,col=self.row,self.col
        
        self.environment=np.zeros(shape=(int(row),int(col)),dtype=str)
        self.visitFrequency=np.zeros(shape=(int(row),int(col)),dtype=int)
        
        self.qtable=np.zeros(shape=(int(row)*int(col),4),dtype=float)
        
        for i in range(int(row)):  
            
            list = input("Enter {} states for row {}: ".format(int(col),i+1)).split() 
            
            for j in range(int(col)):
                self.environment[i][j]=list[j]
                
    def printQTable(self):
        print(self.qtable)
                
    def printEnvironment(self):

        for i in range(self.row):
            for j in range(self.col):
                if(self.location[0]==i and self.location[1]==j):
                    print('\x1b[1;34m'+str(self.environment[i][j])+'\x1b[0m',end=' ')
                else:
                    print(str(self.environment[i][j]),end=" ")
            print(flush=True)
            
    def reward(self):
        
        state=self.environment[self.location[0]][self.location[1]]

        if state=="G":
            
            return 100
        
        elif state=="H":
            
            return -10000
        else:
            
            return 0
       
    
    
    def move(self, move):
        
        if move==1:
            if self.location[0]>0:
                self.location[0]=self.location[0]-1
            
        elif move==2:
            if self.location[1]<self.col-1:
                self.location[1]=self.location[1]+1
        
        elif move==3:
            if self.location[0]<self.row-1:
                self.location[0]=self.location[0]+1
            
        elif move==4:
            if self.location[1]>0:
                self.location[1]=self.location[1]-1
                
    def stateIndex(self):
        return (self.location[0]*self.col)+self.location[1]
                
        
    def whereAt(self):
        
        print("Location [{},{}]".format(self.location[0],self.location[1]))
        if self.location[0]==0 and self.location[1]==0:
            
            print("Available Moves from Here are Right and Down")
      
            
        elif self.location[0]==0 and self.location[1]==self.col-1:

            print("Available Moves from Here are Down and Left")

            
        elif self.location[0]==self.row-1 and self.location[1]==0:
            
            print("Available Moves from Here are Up and Right")
      
            
        elif self.location[0]==self.row-1 and self.location[1]==self.col-1:
            
            print("Available Moves from Here are Up and Left")
     
                
        elif self.location[0]==0 and (self.location[1]!=self.col-1 or self.location[1]!=0):
            
            print("Available Moves from Here are Right,Down and Left")
            
                    
        elif self.location[0]==self.row-1 and (self.location[1]!=self.col-1 or self.location[1]!=0):
            
            print("Available Moves from Here are Up,Right and Left")
            
                    
        elif self.location[1]==0 and (self.location[0]!=self.row-1 or self.location[0]!=0):
            
                print("Available Moves from Here are Up,Right and Down")
            
                        
        elif self.location[1]==self.col-1 and (self.location[0]!=self.row-1 or self.location[0]!=0):
            
            print("Available Moves from Here are Up,Down and Left")


        else:
            
            print("All Moves")
         
        
    

    def chooseMove(self):
        

        if self.location[0]==0 and self.location[1]==0:
            
           
            move=random.choice([2,3])
            
        elif self.location[0]==0 and self.location[1]==self.col-1:

   
            move=random.choice([3,4])
            
        elif self.location[0]==self.row-1 and self.location[1]==0:
            
        
            move=random.choice([1,2])
            
        elif self.location[0]==self.row-1 and self.location[1]==self.col-1:
          
            move=random.choice([1,4])  
                
        elif self.location[0]==0 and (self.location[1]!=self.col-1 or self.location[1]!=0):
            
        
            move=random.choice([2,3,4]) 
                    
        elif self.location[0]==self.row-1 and (self.location[1]!=self.col-1 or self.location[1]!=0):
            
          
            move=random.choice([1,2,4]) 
                    
        elif self.location[1]==0 and (self.location[0]!=self.row-1 or self.location[0]!=0):
            
                
                move=random.choice([1,2,3]) 
                        
        elif self.location[1]==self.col-1 and (self.location[0]!=self.row-1 or self.location[0]!=0):
            
           
            move=random.choice([1,3,4]) 

        else:
            

            move=np.random.randint(4)+1
            
            
        return move

    def moveAround(self):
        
        while 1:
            
            
            move=int(input("Please Enter Move(1-4) 0 to quit: "))
            if move==0: 
                break
            self.whereAt()
            self.move(move)
            self.printEnvironment()
            print(self.stateIndex())
            print("Reward: {}".format(str(self.reward())))
            clear_output(wait=True)
            
    def simulateAgent(self):
        
        start = time.time()
       
        count=0
        reward=0

        while 1:
            self.visitFrequency[self.location[0]][self.location[1]]=self.visitFrequency[self.location[0]][self.location[1]]+1
            count=count+1
            if count%1000000==0:
                print("Count:{}, Reward:{}".format(count/100000,reward))
                print(self.visitFrequency)
            
            
            move=self.chooseMove()
            
            print("Move Chosen at [{},{}] is {}".format(self.location[0],self.location[1],move))
            self.move(move)
            self.whereAt()
            
            if self.reward()==100:
                break
                
            self.printEnvironment()
            print("Reward: {}".format(str(self.reward())))
            time.sleep(0.5)
            
            clear_output(wait=True)
            
        end = time.time()
        
        print("Total Time: {} Seconds".format(end - start));
        
    
    def QLearning(self,learning_rate,discount_factor,iterations):
        
        
        for i in range(iterations):
            if i%100000==0:
                print("Iteration: {}".format(i))
                self.location=[0,0]
            
            while 1:
                self.visitFrequency[self.location[0]][self.location[1]]=self.visitFrequency[self.location[0]][self.location[1]]+1
                move=self.chooseMove()

                t0=self.stateIndex()
                self.move(move)
                t1=self.stateIndex()
                self.qtable[t0][move-1]=(1-learning_rate)*self.qtable[t0][move-1]+learning_rate*(self.reward()+discount_factor*max(self.qtable[t1])-self.qtable[t0][move-1])
                
                
                if self.reward()==100 or self.reward()== -10000:
                    break
    
    def exploit(self):
        
        while 1:
            
            move=np.argmax(self.qtable[self.stateIndex()])+1
            
            direction=""
            
            if move==1:
                direction="north"
            elif move==2:
                direction="right"
            elif move==3:
                direction="down"
            elif move==4:
                direction="left"
                
            print("Move from location [{},{}] is {}".format(self.location[0],self.location[1],direction))
            self.move(move)
            self.printEnvironment()
            time.sleep(1)
            if self.reward()==100 or self.reward()==-100:
                break
            clear_output(wait=True)
        

                  

In [3]:
FrozenLake=FrozenLake()

Welcome to Frozen Lake!! We are a Visual Guide to Help Understand You Q Learning
Please Enter Your Lake Dimensions:

Row: 6
Column: 9
Enter 9 states for row 1: S F F H H H F F G 
Enter 9 states for row 2: F H H F F F H H F 
Enter 9 states for row 3: F F F F F H H H F 
Enter 9 states for row 4: F H H F F F H F F 
Enter 9 states for row 5: F F F F H F F F H 
Enter 9 states for row 6: H H F F H H H F F 


In [4]:
FrozenLake.QLearning(0.5,0.5,10000)

Iteration: 0


In [10]:
list=[1,6,7]

5 in list

False

In [5]:
print(FrozenLake.qtable)

[[ 0.00000000e+00  3.10440858e-09  4.96705373e-08  0.00000000e+00]
 [ 0.00000000e+00  7.76102146e-10 -5.00000000e+03  1.24176343e-08]
 [ 0.00000000e+00 -5.00000000e+03 -5.00000000e+03  3.10440858e-09]
 [ 0.00000000e+00 -5.00000000e+03  3.17891439e-06  7.76102146e-10]
 [ 0.00000000e+00 -4.99916667e+03  1.27156576e-05 -5.00000000e+03]
 [ 0.00000000e+00  3.33333333e+00  3.17891439e-06 -5.00000000e+03]
 [ 0.00000000e+00  1.33333333e+01 -4.99916667e+03 -4.99916667e+03]
 [ 0.00000000e+00  5.33333333e+01 -4.99666667e+03  3.33333333e+00]
 [ 0.00000000e+00  0.00000000e+00  1.33333333e+01  1.33333333e+01]
 [ 1.24176343e-08 -5.00000000e+03  1.98682149e-07  0.00000000e+00]
 [ 3.10440858e-09 -5.00000000e+03  7.94728597e-07  4.96705373e-08]
 [ 7.76102146e-10  3.17891439e-06  3.17891439e-06 -5.00000000e+03]
 [-5.00000000e+03  1.27156576e-05  1.27156576e-05 -5.00000000e+03]
 [-5.00000000e+03  3.17891439e-06  5.08626302e-05  3.17891439e-06]
 [-4.99916667e+03 -4.99916667e+03 -4.99999980e+03  1.27156576e

In [7]:
FrozenLake.location=[0,0]
FrozenLake.exploit()

Move from location [1,8] is north
S F F H H H F F G 
F H H F F F H H F 
F F F F F H H H F 
F H H F F F H F F 
F F F F H F F F H 
H H F F H H H F F 
